- debug: var=fact_ca
- debug: var=fact_cert
- debug: var=fact_key


- name: Deploy Deynamic Admission Controller WebHook
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/webhook.yml') }}"

- name: Create Secrets
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/secrets.yml') }}"

- name: Create RBAC
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/rbac.yml') }}"

- name: Create deployment
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/deployment.yml') }}"

- name: Create service
  k8s:
    state: "{{state}}"
    definition: "{{ lookup('template', 'templates/service.yml') }}"