apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: uacs.uac.ocp.lab
spec:
  group: uac.ocp.lab
  names:
    kind: Uac
    listKind: UacList
    plural: uacs
    singular: uac
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
